import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import Navbar from "@/components/custom/Navbar";
import { cn } from "@/lib/utils";
import ReactQueryProvider from "./ReactQueryProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(`${geistSans.variable} ${geistMono.variable}`, "")}>
        {/* <NextSSRPlugin routerConfig={extractRouterConfig(fileRouter)} /> */}
        <ReactQueryProvider>
          <div className="flex flex-col min-h-[100svh]">
            <Navbar />
            <div className="flex-1 bg-red-500/10">{children}</div>
          </div>
          <Toaster
            toastOptions={{
              classNames: {
                default: "bg-white text-black border-border shadow-lg w-full",
                error: "bg-red-400",
                success: "text-green-400",
                warning: "text-yellow-400",
                info: "bg-blue-400",
              },
            }}
          />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
